ALTER TABLE "CrmRecord" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CrmRecord" ADD COLUMN IF NOT EXISTS "tagColors" JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "tagColors" JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS "CrmRecord_tags_gin_idx" ON "CrmRecord" USING GIN ("tags");
CREATE INDEX IF NOT EXISTS "Activity_tags_gin_idx" ON "Activity" USING GIN ("tags");
